### PR TITLE
Update languages.json

### PR DESCRIPTION
**Pull request by oneyesoneno**

### CODE REVIEW

**Comment by oneyesoneno** [comment]
This branch has conflicts that must be resolved??
i don't understand what is wrong?? someone need to help me :(

**Comment by borispovod** [comment]
@oneyesoneno if this branch contains conflict, i will resolve it in merging process, don't worry

**Comment by oneyesoneno** [comment]
Thanks you

**Comment by borispovod** [comment]
Hello!

What's language?

**Comment by oneyesoneno** [comment]
Hai. It is indonesia language. Ty



-------- Original message --------

**Comment by borispovod** [comment]
Ok, thanks. Going to merge it soon.

**Comment by oneyesoneno** [comment]
Cool man. Ty



-------- Original message --------

**Comment by borispovod** [comment]
Merged

**Pull request closed without merging**
