### PR TITLE
Feature/romanian

### PR DESCRIPTION
**Pull request by ltcrstrbrt**

### CODE REVIEW

**Comment by borispovod** [comment]
Please, remove quotes from file names.
For example:
Content_<ro_RO>.properties

Rename to:
Content_ro_RO.properties

I can't merge due to issue that happens when you have '<' or '>' in file name.

Thanks!

**Comment by ltcrstrbrt** [comment]
It's ok now? Please let me know.

**Comment by borispovod** [comment]
@ltcrstrbrt not yet, you needed to remove quotes '<' and '>' from file names. 
If you have problem with it, ok, i will do it.
Sorry for late answer, a lot of work.

**Comment by ltcrstrbrt** [comment]
It seams that I have some problem with that, It doesn't allow me to modify the file name. 
Can you try to do it? Thanks

**Comment by borispovod** [comment]
Merged by hands, closed.

**Comment by zynis** [comment]
375 eggs awarded

**Pull request closed without merging**
